### ISSUE TITLE
Introduce solved? concept

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-domain#71]
We are making `passed?` true for skipped exercises and it's not consistent. We want an skipped exercise to behave visually as a passed exercise, but it isn't technically in that status. Maybe we should introduce another concept, like `approved?` or `solved?` which represents if the exercise is, well, solved :stuck_out_tongue: ( `passed? || skipped?`) 

Note that we are using `completed?` but it is used with another purpose. It is used to make the assignment polymorphic with an indicator, as `completed?` answers if a certain progress item is, well, completed or not.

See more at #69

**Comment by felipecalvo** [comment]
Here comes SOLVED-19 spreading quickly.

- mumuki-domain: https://github.com/mumuki/mumuki-domain/pull/79
- mumuki-laboratory: https://github.com/mumuki/mumuki-laboratory/pull/1384
- mumukit-core: https://github.com/mumuki/mumukit-core/pull/17
- mumuki-classroom-api: https://github.com/mumuki/mumuki-classroom-api/pull/208
- mumukit-flow: TBA

There are a couple usages of `passed?` in mumukit and mumukit-bridge, but I suspect there's no need to change anything because they're related to running stuff, and nothing will run if we're just skipping.

If there's a need to fix it there, it has to be fixed as in classroom-api - redefining the method, which is a bit dirty.

**Comment by luchotc** [comment]
I think this one is `solved`, right?
